openapi: 3.0.3
info:
  title: Sample Spec
  description: Description
  version: 1.0.0
  license:
    name: Foo
    url: foo
servers:
  - url: https://foo/api/v1
    description: A description
security: []
paths:
  /instances:
    post:
      summary: Create an Instance
      operationId: createInstance
      requestBody:
        content:
          application/json:
            schema:
            # Name conflict here with namedInstanceProperty's config property;
            # Which causes the generation of namedInstanceProperty_configable interface to fail.
              $ref: '#/components/schemas/namedInstancePropertyConfig'
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                properties:
                  instance:
                  # Name conflict here with namedInstancePropertyConfig schema;
                  # Which causes the generation of namedInstanceProperty_configable interface to fail.
                    $ref: '#/components/schemas/namedInstanceProperty'
        '400':
          description: 404 error
components:
  schemas:
    # Name conflict here with namedInstanceProperty's config property
    namedInstancePropertyConfig:
      type: object
      properties:
        information:
          type: object
          required:
            - name
          properties:
            name:
              type: string
              description: Name, a unique identifier for the instance
              example: Sample Instance
    namedInstanceProperty:
      type: object
      properties:
        # Name conflict here with namedInstancePropertyConfig schema
        config:
          type: object
          properties:
            name:
              type: string
