# spec-minimal-foo-bundle shows that the name conflict bug is not limited to the word "Config", but also any other schema name suffix/property clash
openapi: 3.0.3
info:
  title: Sample Spec
  description: Description
  version: 1.0.0
  license:
    name: Foo
    url: foo
servers:
  - url: https://foo/api/v1
    description: A description
security: []
paths:
  /instances:
    post:
      summary: Create an Instance
      operationId: createInstance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/namedInstancePropertyFoo'
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                properties:
                  instance:
                    $ref: '#/components/schemas/namedInstanceProperty'
        '400':
          description: 404 error
components:
  schemas:
    namedInstancePropertyFoo:
      type: object
      properties:
        information:
          type: object
          required:
            - name
          properties:
            name:
              type: string
              description: Name, a unique identifier for the instance
              example: Sample Instance
    namedInstanceProperty:
      type: object
      properties:
        config:
          type: object
          properties:
            name:
              type: string
        foo:
          type: object
          properties:
            name:
              type: string
